sudo: required
dist: trusty
language: node_js
node_js:
  - '10.15.1'

addons:
  chrome: stable
services:
  - xvfb

install:
  - npm install -g angular-cli codacy-coverage
  - npm install

before_script:
  - TRAVIS_NODE_PATH=$(dirname $(nvm which $TRAVIS_NODE_VERSION))
  - export PATH="${PATH}:${TRAVIS_NODE_PATH}"

script:
  - ng lint
  - ng test --watch=false --code-coverage
  - npm run e2e
  - ng build --prod --base-href /earthquakes/eventpage/

after_success:
  - cat coverage/lcov.info | codacy-coverage --verbose
