sudo: required
dist: xenial
language: node_js
node_js:
  - '10.15.1'

addons:
  chrome: stable
services:
  - xvfb

install:
  - npm install -g codacy-coverage
  - npm install

before_script:
  - TRAVIS_NODE_PATH=$(dirname $(nvm which $TRAVIS_NODE_VERSION))
  - export PATH="${PATH}:${TRAVIS_NODE_PATH}"

script:
  - npm run lint
  - npm run test -- --watch=false --code-coverage
  - npm run e2e
  - npm run build -- --base-href /earthquakes/eventpage/

after_success:
  - cat coverage/lcov.info | codacy-coverage --verbose
